server:
  port: 8083

spring:
  application:
    name: messages-service

  cache:
    type: redis   # activa cache redis

  data:
    redis:
      host: localhost     # Redis corre en tu máquina / contenedor local
      port: 6379          # Puerto por defecto
      password:           # SIN contraseña en local
      ssl:
        enabled: false    # SIN SSL en local

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,caches

gateway:
  security:
    header: X-Gateway-Request
    secret: AdminUco2024   # ← valor normal, sin variables
