spring.application.name=messages-service

# Observabilidad - OpenTelemetry / Datadog
otel.java.global-autoconfigure.enabled=true
otel.exporter.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://${OTEL_EXPORTER_OTLP_HOST:localhost}:${OTEL_EXPORTER_OTLP_PORT:4318}}
otel.exporter.otlp.protocol=${OTEL_EXPORTER_OTLP_PROTOCOL:http/protobuf}
otel.metrics.exporter=${OTEL_METRICS_EXPORTER:otlp}
otel.traces.exporter=${OTEL_TRACES_EXPORTER:otlp}
otel.logs.exporter=${OTEL_LOGS_EXPORTER:none}
otel.resource.attributes=service.name=${OTEL_SERVICE_NAME:${spring.application.name}},service.version=${OTEL_SERVICE_VERSION:0.0.1},deployment.environment=${OTEL_ENV:local}
otel.exporter.otlp.headers=${OTEL_EXPORTER_OTLP_HEADERS:}

# Actuator / Prometheus
management.endpoints.web.exposure.include=health,info,prometheus
management.prometheus.metrics.export.enabled=false
management.metrics.tags.application=${spring.application.name}
spring.autoconfigure.exclude=io.opentelemetry.instrumentation.spring.autoconfigure.OpenTelemetryAutoConfiguration
