server:
  port: 8083

spring:
  application:
    name: messages-service

# ❌ Quita por completo la sección oauth2.resourceserver.jwt

gateway:
  security:
    header: X-Gateway-Request
    secret: AdminUco2024
