spring.application.name=UcoChallengeGateway

# Puerto del Gateway
server.port=8081

# Configuracion de Auth0 (Resource Server)
# El dominio de Auth0 que usaste: dev-kkp1gdpup1nvbr6q.us.auth0.com
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-kkp1gdup1nvbr6qj.us.auth0.com/
spring.security.oauth2.resourceserver.jwt.audience=https://api.ucochallenge.com


# Enrutamiento: Redirige /api/v1/usuarios/** al Microservicio (8080)
spring.cloud.gateway.server.webflux.routes[0].id=uco-backend
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8080
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=AddRequestHeader=X-Gateway-Request, AdminUco2024


# Cache
spring.cache.type=redis
spring.data.redis.url=${REDIS_URL:rediss://default:AU7sAAIncDI5YWYzZjJiZDA2ZjI0YTNiYTNiMDE2YWM4ZGY5ZGJhM3AyMjAyMDQ@real-eft-20204.upstash.io:6379}
spring.data.redis.host=${REDIS_HOST:real-eft-20204.upstash.io}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.username=${REDIS_USERNAME: default}
spring.data.redis.password=${REDIS_PASSWORD:AU7sAAIncDI5YWYzZjJiZDA2ZjI0YTNiYTNiMDE2YWM4ZGY5ZGJhM3AyMjAyMDQ}
spring.data.redis.ssl.enabled=${REDIS_SSL_ENABLED:false}
spring.data.redis.repositories.enabled=false

# Observabilidad - OpenTelemetry / Datadog
otel.java.global-autoconfigure.enabled=true
otel.exporter.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://${OTEL_EXPORTER_OTLP_HOST:localhost}:${OTEL_EXPORTER_OTLP_PORT:4318}}
otel.exporter.otlp.protocol=${OTEL_EXPORTER_OTLP_PROTOCOL:http/protobuf}
otel.metrics.exporter=${OTEL_METRICS_EXPORTER:otlp}
otel.traces.exporter=${OTEL_TRACES_EXPORTER:otlp}
otel.logs.exporter=${OTEL_LOGS_EXPORTER:none}
otel.resource.attributes=service.name=${OTEL_SERVICE_NAME:${spring.application.name}},service.version=${OTEL_SERVICE_VERSION:0.0.1},deployment.environment=${OTEL_ENV:local}
otel.exporter.otlp.headers=${OTEL_EXPORTER_OTLP_HEADERS:}


# Actuator / Prometheus
management.endpoints.web.exposure.include=health,info,prometheus
management.prometheus.metrics.export.enabled=false
management.metrics.tags.application=${spring.application.name}
spring.autoconfigure.exclude=io.opentelemetry.instrumentation.spring.autoconfigure.OpenTelemetryAutoConfiguration