server:
  port: 8082

spring:
  application:
    name: parameters-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-kkp1gdup1nvbr6qj.us.auth0.com/  # tu tenant Auth0
